# Generated by Django 4.1.4 on 2023-01-04 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batch_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('data', models.JSONField(default=dict)),
            ],
        ),
    ]
